name: Deploy TypeScript Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build TypeScript
      run: npm run build

    - name: Create settings.json File
      run: |
        echo '{ "mongodb": "${{secrets.MONGODB}}", "JWTKey": "${{secrets.JWTKEY}}", "smtpPassword" : "${{secrets.SMTPPASSWORD}}", "smtpUsername" : "${{secrets.SMTPUSERNAME}}", "smtpPort" : ${{secrets.SMTPPORT}}, "smtpHost" : "${{secrets.SMTPHOST}}", "smtpFrom" : "${{secrets.SMTPFROM}}", "smtpSecure" : ${{secrets.SMTPSECURE}} }' > ./build/settings.json

    - name: FTP Files to Server
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ${{secrets.SSH_SERVER}}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        local-dir: ./build/
        server-dir: /home/crash/apps/velocevent/newbuild/
        port: 22
        protocol: ftps
        timeout: 60000

    - name: SSH Key Setup
      uses: webfactory/ssh-agent@v0.5.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH to Server and Stop Server
      run: |
        ssh -T ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER }} << 'ENDSSH'
        cd /home/crash/apps/velocevent/
        ./stop
        ENDSSH

    - name: Run Start Script on Server
      run: |
        ssh -T ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER }} << 'ENDSSH'
        cd /home/crash/apps/velocevent/
        ./start
        ENDSSH

