name: Deploy TypeScript Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build TypeScript
      run: npm run build

    - name: Create settings.json File
      run: |
        $settings = @{
          mongodb = "${{ secrets.MONGODB }}"
          JWTKey = "${{ secrets.JWTKEY }}"
          smtpPassword = "${{ secrets.SMTPPASSWORD }}"
          smtpUsername = "${{ secrets.SMTPUSERNAME }}"
          smtpPort = ${{ secrets.SMTPPORT }}
          smtpHost = "${{ secrets.SMTPHOST }}"
          smtpFrom = "${{ secrets.SMTPFROM }}"
          smtpSecure = ${{ secrets.SMTPSECURE }}
        } | ConvertTo-Json -Compress
        Set-Content -Path ./build/settings.json -Value $settings

    - name: Deploy Files to Server via SCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        REMOTE_DIR: /home/crash/apps/velocevent/newbuild/
      run: |
        # Install OpenSSH if it's not already
        Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
    
        # Setup SSH Key
        $sshDir = "$env:USERPROFILE\.ssh"
        $privateKeyFile = "$sshDir\id_rsa"
        New-Item -ItemType Directory -Force -Path $sshDir
        $env:SSH_PRIVATE_KEY | Out-File -FilePath $privateKeyFile -Encoding ascii
        & icacls.exe $privateKeyFile /inheritance:r /grant:r "$($env:USERNAME):R"
        @"
        Host $env:SSH_SERVER
            User $env:SSH_USERNAME
            IdentityFile $privateKeyFile
            StrictHostKeyChecking no
        "@ | Set-Content -Path "$sshDir\config"
    
        # Ensure Remote Directory Exists
        ssh $env:SSH_USERNAME@$env:SSH_SERVER "mkdir -p $env:REMOTE_DIR"
    
        # SCP Files to Remote Directory
        scp -o ConnectTimeout=60 -r .\build\* $env:SSH_USERNAME@$env:SSH_SERVER:"$env:REMOTE_DIR"
