name: Deploy TypeScript Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build TypeScript
      run: npm run build

    - name: Create settings.json File
      run: |
        echo '{ "mongodb": "${{ secrets.MONGODB }}", "JWTKey": "${{ secrets.JWTKEY }}", "smtpPassword" : "${{ secrets.SMTPPASSWORD }}", "smtpUsername" : "${{ secrets.SMTPUSERNAME }}", "smtpPort" : ${{ secrets.SMTPPORT }}, "smtpHost" : "${{ secrets.SMTPHOST }}", "smtpFrom" : "${{ secrets.SMTPFROM }}", "smtpSecure" : ${{ secrets.SMTPSECURE }} }' > ./build/settings.json

    - name: Install OpenSSH Client (Windows)
      run: Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

    - name: Ensure Remote Directory Exists
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        $password = ConvertTo-SecureString $env:SSH_PASSWORD -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ($env:SSH_USERNAME, $password)
        ssh -v $env:SSH_USERNAME@$env:SSH_SERVER -pw $credential.GetNetworkCredential().Password "mkdir -p /home/crash/apps/velocevent/newbuild/"

    - name: Deploy Files to Server via SCP
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        $password = ConvertTo-SecureString $env:SSH_PASSWORD -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ($env:SSH_USERNAME, $password)
        scp -v -o ConnectTimeout=60 -pw $credential.GetNetworkCredential().Password -r .\build\* $env:SSH_USERNAME@$env:SSH_SERVER:/home/crash/apps/velocevent/newbuild/
