name: Deploy TypeScript Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build TypeScript
      run: npm run build

    - name: Create settings.json File
      run: |
        echo '{ "mongodb": "${{secrets.MONGODB}}", "JWTKey": "${{secrets.JWTKEY}}", "smtpPassword" : "${{secrets.SMTPPASSWORD}}", "smtpUsername" : "${{secrets.SMTPUSERNAME}}", "smtpPort" : ${{secrets.SMTPPORT}}, "smtpHost" : "${{secrets.SMTPHOST}}", "smtpFrom" : "${{secrets.SMTPFROM}}", "smtpSecure" : ${{secrets.SMTPSECURE}} }' > ./build/settings.json

    - name: Deploy Files to Server via SCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PORT: 22 # Update with your server's SSH port if it's not the default
        REMOTE_DIR: /home/crash/apps/velocevent/newbuild/
      run: |
        # Install OpenSSH if it's not already
        Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
    
        # Set up SSH Key and SSH Config
        $sshDir = "$env:USERPROFILE\.ssh"
        $privateKeyFile = "$sshDir\id_rsa"
        New-Item -ItemType Directory -Force -Path $sshDir
        $env:SSH_PRIVATE_KEY | Out-File -FilePath $privateKeyFile -Encoding ascii
        Set-Content -Path "$sshDir\config" -Value "Host $env:SSH_SERVER `n  IdentityFile $privateKeyFile `n  Port $env:SSH_PORT `n  User $env:SSH_USERNAME `n  StrictHostKeyChecking no"
        & icacls.exe $privateKeyFile /inheritance:r /grant:r "$($env:USERNAME):R"
    
        # Execute SCP Command to Transfer Files
        scp -o ConnectTimeout=60 -r .\build\* $env:SSH_USERNAME@$env:SSH_SERVER:"$env:REMOTE_DIR"
    
    - name: SSH Key Setup
      uses: webfactory/ssh-agent@v0.5.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH to Server and Stop Server
      run: |
        ssh -T ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER }} << 'ENDSSH'
        cd /home/crash/apps/velocevent/
        ./stop
        ENDSSH

    - name: Run Start Script on Server
      run: |
        ssh -T ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER }} << 'ENDSSH'
        cd /home/crash/apps/velocevent/
        ./start
        ENDSSH

